services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - foyer-network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8091:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - foyer-network
    restart: unless-stopped

  discovery-server:
    image: attiaimeed/discovery-server:${BUILD_TAG:-latest}
    container_name: discovery-server
    ports:
      - "8095:8095"
    networks:
      - foyer-network
    restart: unless-stopped

  api-gateway:
    image: attiaimeed/api-gateway:${BUILD_TAG:-latest}
    container_name: api-gateway
    ports:
      - "8090:8090"
    depends_on:
      - discovery-server
    networks:
      - foyer-network
    restart: unless-stopped
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8095/eureka

  foyer-service:
    image: attiaimeed/foyer-service:${BUILD_TAG:-latest}
    container_name: foyer-service
    ports:
      - "8086:8086"
    depends_on:
      - discovery-server
      - mysql
    networks:
      - foyer-network
    restart: unless-stopped
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8095/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

volumes:
  mysql_data:

networks:
  foyer-network:
    driver: bridge